import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

//这在 Node.js 中运行 - 不要在此处使用客户端代码（浏览器 API、JSX...

/**
 * 创建边栏使您能够：
 - 创建有序的文档组
 - 为该组的每个文档呈现一个侧边栏
 - 提供下一个/上一个导航

侧边栏可以从文件系统生成，也可以在此处显式定义。
 根据需要创建任意数量的侧边栏。
 */
const sidebars: SidebarsConfig = {
  // 默认情况下，Docusaurus 会从 docs 文件夹结构生成侧边栏
  minecraftLaunchSidebar: [
    {type: 'autogenerated', dirName: 'MinecraftLaunch'}
  ],
  wonderLabSidebar: [
    {type: 'autogenerated', dirName: 'WonderLab'}
  ],
  designSidebar: [
    {type: 'autogenerated', dirName: 'design'}
  ],
  aboutSidebar: [
    {type: 'autogenerated', dirName: 'About'}
  ]

  // 但您可以手动创建侧边栏
  /*
  minecraftLaunchSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
